server:
  port: 9010
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: yiyi-cloud-eureka-server
#mybatis-plus配置控制台打印完整带参数SQL语句
logging:
  level:
    com.company.management.system: debug