server:
  port: 9020
spring:
  application:
    name: yiyi-bams-boot
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yiyi?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: yiyi
    password: yiyi123
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka
logging:
  config: classpath:logback-spring.xml
